-- MySQL Script generated by MySQL Workbench
-- sáb 09 abr 2022 23:11:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema SafeZone
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `SafeZone` ;

-- -----------------------------------------------------
-- Schema SafeZone
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SafeZone` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `SafeZone` ;

-- -----------------------------------------------------
-- Table `SafeZone`.`Recomendados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeZone`.`Recomendados` (
  `ID_lugar` INT NOT NULL,
  `Nombre` TEXT NOT NULL,
  `Calificación` DOUBLE NOT NULL,
  `Descripción` TEXT NOT NULL,
  PRIMARY KEY (`ID_lugar`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SafeZone`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeZone`.`Lugar` (
  `ID_lugar` INT NOT NULL AUTO_INCREMENT,
  `Nombre` TEXT NOT NULL,
  `Tipo_de_lugar` TEXT NOT NULL,
  `Calificación` DOUBLE NOT NULL,
  `Reporte` TEXT NOT NULL,
  `Descripción` TEXT NOT NULL,
  `Recomendados_ID_lugar` INT NOT NULL,
  PRIMARY KEY (`ID_lugar`),
  CONSTRAINT `fk_Lugar_Recomendados1`
    FOREIGN KEY (`Recomendados_ID_lugar`)
    REFERENCES `SafeZone`.`Recomendados` (`ID_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_Lugar_Recomendados1_idx` ON `SafeZone`.`Lugar` (`Recomendados_ID_lugar` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SafeZone`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeZone`.`Usuarios` (
  `ID_usuario` INT NOT NULL AUTO_INCREMENT,
  `Nombre` TEXT NOT NULL,
  `Apellido` TEXT NOT NULL,
  `Email` VARCHAR(50) NOT NULL,
  `contraseña` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`ID_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `SafeZone`.`Calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeZone`.`Calificaciones` (
  `ID_calificación` INT NOT NULL AUTO_INCREMENT,
  `ID_lugar` INT NOT NULL,
  `Encuesta` INT NOT NULL,
  `Puntuación` DOUBLE NOT NULL,
  `Comentario` VARCHAR(255) NOT NULL,
  `Usuarios_ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_calificación`, `Usuarios_ID_usuario`),
  CONSTRAINT `Calificaciones_ibfk_1`
    FOREIGN KEY (`ID_lugar`)
    REFERENCES `SafeZone`.`Lugar` (`ID_lugar`),
  CONSTRAINT `fk_Calificaciones_Usuarios1`
    FOREIGN KEY (`Usuarios_ID_usuario`)
    REFERENCES `SafeZone`.`Usuarios` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ID_lugar` ON `SafeZone`.`Calificaciones` (`ID_lugar` ASC) VISIBLE;

CREATE INDEX `fk_Calificaciones_Usuarios1_idx` ON `SafeZone`.`Calificaciones` (`Usuarios_ID_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SafeZone`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeZone`.`Reportes` (
  `ID_reporte` INT NOT NULL AUTO_INCREMENT,
  `ID_lugar` INT NOT NULL,
  `Nombre_lugar` TEXT NOT NULL,
  `Tipo_de_delito` TEXT NOT NULL,
  `Descrpción` VARCHAR(255) NOT NULL,
  `Usuarios_ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_reporte`, `Usuarios_ID_usuario`),
  CONSTRAINT `Reportes_ibfk_1`
    FOREIGN KEY (`ID_lugar`)
    REFERENCES `SafeZone`.`Lugar` (`ID_lugar`),
  CONSTRAINT `fk_Reportes_Usuarios1`
    FOREIGN KEY (`Usuarios_ID_usuario`)
    REFERENCES `SafeZone`.`Usuarios` (`ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `ID_lugar` ON `SafeZone`.`Reportes` (`ID_lugar` ASC) VISIBLE;

CREATE INDEX `fk_Reportes_Usuarios1_idx` ON `SafeZone`.`Reportes` (`Usuarios_ID_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `SafeZone`.`Mapa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SafeZone`.`Mapa` (
  `ID_indicador` INT NOT NULL AUTO_INCREMENT,
  `Tipo_de_delito` TEXT NOT NULL,
  `Reportes_ID_reporte` INT NOT NULL,
  `Reportes_Usuarios_ID_usuario` INT NOT NULL,
  PRIMARY KEY (`ID_indicador`),
  CONSTRAINT `fk_Indicadores_Reportes1`
    FOREIGN KEY (`Reportes_ID_reporte` , `Reportes_Usuarios_ID_usuario`)
    REFERENCES `SafeZone`.`Reportes` (`ID_reporte` , `Usuarios_ID_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `fk_Indicadores_Reportes1_idx` ON `SafeZone`.`Mapa` (`Reportes_ID_reporte` ASC, `Reportes_Usuarios_ID_usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
